[2021-01-25 17:09:36,430] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.load_data 2021-01-25T17:09:31.045821+00:00 [queued]>
[2021-01-25 17:09:36,456] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.load_data 2021-01-25T17:09:31.045821+00:00 [queued]>
[2021-01-25 17:09:36,456] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 17:09:36,457] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-01-25 17:09:36,457] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 17:09:36,502] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): load_data> on 2021-01-25T17:09:31.045821+00:00
[2021-01-25 17:09:36,506] {standard_task_runner.py:54} INFO - Started process 51227 to run task
[2021-01-25 17:09:36,535] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'load_data', '2021-01-25T17:09:31.045821+00:00', '--job_id', '31', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmpugmmiuk_']
[2021-01-25 17:09:36,540] {standard_task_runner.py:78} INFO - Job 31: Subtask load_data
[2021-01-25 17:09:36,620] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.load_data 2021-01-25T17:09:31.045821+00:00 [running]> 3f8da9634a9c
[2021-01-25 17:09:36,696] {logging_mixin.py:112} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py:2612: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,
[2021-01-25 17:09:37,093] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-01-25 17:09:37,112] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=load_data, execution_date=20210125T170931, start_date=20210125T170936, end_date=20210125T170937
[2021-01-25 17:09:41,412] {local_task_job.py:102} INFO - Task exited with return code 0
