[2021-01-21 20:19:07,688] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.load_data 2021-01-21T20:19:01.193746+00:00 [queued]>
[2021-01-21 20:19:07,745] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.load_data 2021-01-21T20:19:01.193746+00:00 [queued]>
[2021-01-21 20:19:07,746] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 20:19:07,747] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-01-21 20:19:07,747] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 20:19:07,803] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): load_data> on 2021-01-21T20:19:01.193746+00:00
[2021-01-21 20:19:07,808] {standard_task_runner.py:54} INFO - Started process 285 to run task
[2021-01-21 20:19:07,842] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'load_data', '2021-01-21T20:19:01.193746+00:00', '--job_id', '3', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmpm62rrwio']
[2021-01-21 20:19:07,848] {standard_task_runner.py:78} INFO - Job 3: Subtask load_data
[2021-01-21 20:19:07,953] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.load_data 2021-01-21T20:19:01.193746+00:00 [running]> 3f8da9634a9c
[2021-01-21 20:19:08,056] {logging_mixin.py:112} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py:2612: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,
[2021-01-21 20:19:08,247] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-01-21 20:19:08,271] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=load_data, execution_date=20210121T201901, start_date=20210121T201907, end_date=20210121T201908
[2021-01-21 20:19:12,497] {local_task_job.py:102} INFO - Task exited with return code 0
